[package]
name = "quick-magic"
version = "0.1.0"
authors = ["NaokiM03 <mattsun.phone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard-win = "3.0.1"
rust-embed = "5.5.0"
